# Generated by Django 4.2.22 on 2025-06-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparelho', models.CharField(max_length=255)),
                ('consumo', models.CharField(max_length=20)),
                ('tempo', models.CharField(max_length=100)),
                ('dias_de_uso', models.IntegerField(default=0)),
            ],
        ),
    ]
