# Generated by Django 4.2.22 on 2025-06-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_gestao_tempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('gestao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestao.gestao')),
                ('consumo_mensal_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_mensal_reais', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
